// Comprehensive list of all currencies supported by ExchangeRate-API
// Data sourced from https://www.exchangerate-api.com/docs/supported-currencies

export const ALL_CURRENCIES = {
  AED: { name: "UAE Dirham", symbol: "د.إ", country: "United Arab Emirates" },
  AFN: { name: "Afghan Afghani", symbol: "؋", country: "Afghanistan" },
  ALL: { name: "Albanian Lek", symbol: "L", country: "Albania" },
  AMD: { name: "Armenian Dram", symbol: "֏", country: "Armenia" },
  ANG: {
    name: "Netherlands Antillian Guilder",
    symbol: "ƒ",
    country: "Netherlands Antilles",
  },
  AOA: { name: "Angolan Kwanza", symbol: "Kz", country: "Angola" },
  ARS: { name: "Argentine Peso", symbol: "$", country: "Argentina" },
  AUD: { name: "Australian Dollar", symbol: "A$", country: "Australia" },
  AWG: { name: "Aruban Florin", symbol: "ƒ", country: "Aruba" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼", country: "Azerbaijan" },
  BAM: {
    name: "Bosnia and Herzegovina Mark",
    symbol: "KM",
    country: "Bosnia and Herzegovina",
  },
  BBD: { name: "Barbados Dollar", symbol: "$", country: "Barbados" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh" },
  BGN: { name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب", country: "Bahrain" },
  BIF: { name: "Burundian Franc", symbol: "Fr", country: "Burundi" },
  BMD: { name: "Bermudian Dollar", symbol: "$", country: "Bermuda" },
  BND: { name: "Brunei Dollar", symbol: "$", country: "Brunei" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs.", country: "Bolivia" },
  BRL: { name: "Brazilian Real", symbol: "R$", country: "Brazil" },
  BSD: { name: "Bahamian Dollar", symbol: "$", country: "Bahamas" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu.", country: "Bhutan" },
  BWP: { name: "Botswana Pula", symbol: "P", country: "Botswana" },
  BYN: { name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
  BZD: { name: "Belize Dollar", symbol: "$", country: "Belize" },
  CAD: { name: "Canadian Dollar", symbol: "C$", country: "Canada" },
  CDF: {
    name: "Congolese Franc",
    symbol: "Fr",
    country: "Democratic Republic of Congo",
  },
  CHF: { name: "Swiss Franc", symbol: "Fr", country: "Switzerland" },
  CLP: { name: "Chilean Peso", symbol: "$", country: "Chile" },
  CNY: { name: "Chinese Renminbi", symbol: "¥", country: "China" },
  COP: { name: "Colombian Peso", symbol: "$", country: "Colombia" },
  CRC: { name: "Costa Rican Colon", symbol: "₡", country: "Costa Rica" },
  CUP: { name: "Cuban Peso", symbol: "$", country: "Cuba" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$", country: "Cape Verde" },
  CZK: { name: "Czech Koruna", symbol: "Kč", country: "Czech Republic" },
  DJF: { name: "Djiboutian Franc", symbol: "Fr", country: "Djibouti" },
  DKK: { name: "Danish Krone", symbol: "kr", country: "Denmark" },
  DOP: { name: "Dominican Peso", symbol: "$", country: "Dominican Republic" },
  DZD: { name: "Algerian Dinar", symbol: "د.ج", country: "Algeria" },
  EGP: { name: "Egyptian Pound", symbol: "£", country: "Egypt" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk", country: "Eritrea" },
  ETB: { name: "Ethiopian Birr", symbol: "Br", country: "Ethiopia" },
  EUR: { name: "Euro", symbol: "€", country: "European Union" },
  FJD: { name: "Fiji Dollar", symbol: "$", country: "Fiji" },
  FKP: {
    name: "Falkland Islands Pound",
    symbol: "£",
    country: "Falkland Islands",
  },
  FOK: { name: "Faroese Króna", symbol: "kr", country: "Faroe Islands" },
  GBP: { name: "Pound Sterling", symbol: "£", country: "United Kingdom" },
  GEL: { name: "Georgian Lari", symbol: "₾", country: "Georgia" },
  GGP: { name: "Guernsey Pound", symbol: "£", country: "Guernsey" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵", country: "Ghana" },
  GIP: { name: "Gibraltar Pound", symbol: "£", country: "Gibraltar" },
  GMD: { name: "Gambian Dalasi", symbol: "D", country: "Gambia" },
  GNF: { name: "Guinean Franc", symbol: "Fr", country: "Guinea" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q", country: "Guatemala" },
  GYD: { name: "Guyanese Dollar", symbol: "$", country: "Guyana" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$", country: "Hong Kong" },
  HNL: { name: "Honduran Lempira", symbol: "L", country: "Honduras" },
  HRK: { name: "Croatian Kuna", symbol: "kn", country: "Croatia" },
  HTG: { name: "Haitian Gourde", symbol: "G", country: "Haiti" },
  HUF: { name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp", country: "Indonesia" },
  ILS: { name: "Israeli New Shekel", symbol: "₪", country: "Israel" },
  IMP: { name: "Manx Pound", symbol: "£", country: "Isle of Man" },
  INR: { name: "Indian Rupee", symbol: "₹", country: "India" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq" },
  IRR: { name: "Iranian Rial", symbol: "﷼", country: "Iran" },
  ISK: { name: "Icelandic Króna", symbol: "kr", country: "Iceland" },
  JEP: { name: "Jersey Pound", symbol: "£", country: "Jersey" },
  JMD: { name: "Jamaican Dollar", symbol: "$", country: "Jamaica" },
  JOD: { name: "Jordanian Dinar", symbol: "د.ا", country: "Jordan" },
  JPY: { name: "Japanese Yen", symbol: "¥", country: "Japan" },
  KES: { name: "Kenyan Shilling", symbol: "Sh", country: "Kenya" },
  KGS: { name: "Kyrgyzstani Som", symbol: "с", country: "Kyrgyzstan" },
  KHR: { name: "Cambodian Riel", symbol: "៛", country: "Cambodia" },
  KID: { name: "Kiribati Dollar", symbol: "$", country: "Kiribati" },
  KMF: { name: "Comorian Franc", symbol: "Fr", country: "Comoros" },
  KRW: { name: "South Korean Won", symbol: "₩", country: "South Korea" },
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك", country: "Kuwait" },
  KYD: {
    name: "Cayman Islands Dollar",
    symbol: "$",
    country: "Cayman Islands",
  },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸", country: "Kazakhstan" },
  LAK: { name: "Lao Kip", symbol: "₭", country: "Laos" },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon" },
  LKR: { name: "Sri Lanka Rupee", symbol: "Rs", country: "Sri Lanka" },
  LRD: { name: "Liberian Dollar", symbol: "$", country: "Liberia" },
  LSL: { name: "Lesotho Loti", symbol: "L", country: "Lesotho" },
  LYD: { name: "Libyan Dinar", symbol: "ل.د", country: "Libya" },
  MAD: { name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco" },
  MDL: { name: "Moldovan Leu", symbol: "L", country: "Moldova" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar", country: "Madagascar" },
  MKD: { name: "Macedonian Denar", symbol: "ден", country: "North Macedonia" },
  MMK: { name: "Burmese Kyat", symbol: "K", country: "Myanmar" },
  MNT: { name: "Mongolian Tögrög", symbol: "₮", country: "Mongolia" },
  MOP: { name: "Macanese Pataca", symbol: "P", country: "Macau" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM", country: "Mauritania" },
  MUR: { name: "Mauritian Rupee", symbol: "₨", country: "Mauritius" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf", country: "Maldives" },
  MWK: { name: "Malawian Kwacha", symbol: "MK", country: "Malawi" },
  MXN: { name: "Mexican Peso", symbol: "$", country: "Mexico" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia" },
  MZN: { name: "Mozambican Metical", symbol: "MT", country: "Mozambique" },
  NAD: { name: "Namibian Dollar", symbol: "$", country: "Namibia" },
  NGN: { name: "Nigerian Naira", symbol: "₦", country: "Nigeria" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$", country: "Nicaragua" },
  NOK: { name: "Norwegian Krone", symbol: "kr", country: "Norway" },
  NPR: { name: "Nepalese Rupee", symbol: "₨", country: "Nepal" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$", country: "New Zealand" },
  OMR: { name: "Omani Rial", symbol: "ر.ع.", country: "Oman" },
  PAB: { name: "Panamanian Balboa", symbol: "B/.", country: "Panama" },
  PEN: { name: "Peruvian Sol", symbol: "S/", country: "Peru" },
  PGK: {
    name: "Papua New Guinean Kina",
    symbol: "K",
    country: "Papua New Guinea",
  },
  PHP: { name: "Philippine Peso", symbol: "₱", country: "Philippines" },
  PKR: { name: "Pakistani Rupee", symbol: "₨", country: "Pakistan" },
  PLN: { name: "Polish Złoty", symbol: "zł", country: "Poland" },
  PYG: { name: "Paraguayan Guaraní", symbol: "₲", country: "Paraguay" },
  QAR: { name: "Qatari Riyal", symbol: "ر.ق", country: "Qatar" },
  RON: { name: "Romanian Leu", symbol: "lei", country: "Romania" },
  RSD: { name: "Serbian Dinar", symbol: "дин", country: "Serbia" },
  RUB: { name: "Russian Ruble", symbol: "₽", country: "Russia" },
  RWF: { name: "Rwandan Franc", symbol: "Fr", country: "Rwanda" },
  SAR: { name: "Saudi Riyal", symbol: "ر.س", country: "Saudi Arabia" },
  SBD: {
    name: "Solomon Islands Dollar",
    symbol: "$",
    country: "Solomon Islands",
  },
  SCR: { name: "Seychellois Rupee", symbol: "₨", country: "Seychelles" },
  SDG: { name: "Sudanese Pound", symbol: "£", country: "Sudan" },
  SEK: { name: "Swedish Krona", symbol: "kr", country: "Sweden" },
  SGD: { name: "Singapore Dollar", symbol: "S$", country: "Singapore" },
  SHP: { name: "Saint Helena Pound", symbol: "£", country: "Saint Helena" },
  SLE: { name: "Sierra Leonean Leone", symbol: "Le", country: "Sierra Leone" },
  SLL: {
    name: "Sierra Leonean Leone (Old)",
    symbol: "Le",
    country: "Sierra Leone",
  },
  SOS: { name: "Somali Shilling", symbol: "Sh", country: "Somalia" },
  SRD: { name: "Surinamese Dollar", symbol: "$", country: "Suriname" },
  SSP: { name: "South Sudanese Pound", symbol: "£", country: "South Sudan" },
  STN: {
    name: "São Tomé and Príncipe Dobra",
    symbol: "Db",
    country: "São Tomé and Príncipe",
  },
  SYP: { name: "Syrian Pound", symbol: "£", country: "Syria" },
  SZL: { name: "Eswatini Lilangeni", symbol: "L", country: "Eswatini" },
  THB: { name: "Thai Baht", symbol: "฿", country: "Thailand" },
  TJS: { name: "Tajikistani Somoni", symbol: "ЅМ", country: "Tajikistan" },
  TMT: { name: "Turkmenistan Manat", symbol: "m", country: "Turkmenistan" },
  TND: { name: "Tunisian Dinar", symbol: "د.ت", country: "Tunisia" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$", country: "Tonga" },
  TRY: { name: "Turkish Lira", symbol: "₺", country: "Turkey" },
  TTD: {
    name: "Trinidad and Tobago Dollar",
    symbol: "$",
    country: "Trinidad and Tobago",
  },
  TVD: { name: "Tuvaluan Dollar", symbol: "$", country: "Tuvalu" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$", country: "Taiwan" },
  TZS: { name: "Tanzanian Shilling", symbol: "Sh", country: "Tanzania" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴", country: "Ukraine" },
  UGX: { name: "Ugandan Shilling", symbol: "Sh", country: "Uganda" },
  USD: { name: "United States Dollar", symbol: "$", country: "United States" },
  UYU: { name: "Uruguayan Peso", symbol: "$", country: "Uruguay" },
  UZS: { name: "Uzbekistani Som", symbol: "so'm", country: "Uzbekistan" },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs.", country: "Venezuela" },
  VND: { name: "Vietnamese Đồng", symbol: "₫", country: "Vietnam" },
  VUV: { name: "Vanuatu Vatu", symbol: "Vt", country: "Vanuatu" },
  WST: { name: "Samoan Tālā", symbol: "T", country: "Samoa" },
  XAF: {
    name: "Central African CFA Franc",
    symbol: "Fr",
    country: "Central Africa",
  },
  XCD: {
    name: "East Caribbean Dollar",
    symbol: "$",
    country: "East Caribbean",
  },
  XDR: { name: "Special Drawing Rights", symbol: "SDR", country: "IMF" },
  XOF: { name: "West African CFA Franc", symbol: "Fr", country: "West Africa" },
  XPF: { name: "CFP Franc", symbol: "Fr", country: "French Pacific" },
  YER: { name: "Yemeni Rial", symbol: "﷼", country: "Yemen" },
  ZAR: { name: "South African Rand", symbol: "R", country: "South Africa" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK", country: "Zambia" },
  ZWL: { name: "Zimbabwean Dollar", symbol: "$", country: "Zimbabwe" },
};

// Get currency details
export function getCurrencyDetails(code) {
  return (
    ALL_CURRENCIES[code] || { name: code, symbol: "$", country: "Unknown" }
  );
}

// Get all currency codes as array
export function getAllCurrencyCodes() {
  return Object.keys(ALL_CURRENCIES).sort();
}

// Search currencies by code, name, or country
export function searchCurrencies(searchTerm) {
  const term = searchTerm.toLowerCase();
  return Object.entries(ALL_CURRENCIES)
    .filter(
      ([code, details]) =>
        code.toLowerCase().includes(term) ||
        details.name.toLowerCase().includes(term) ||
        details.country.toLowerCase().includes(term)
    )
    .map(([code, details]) => ({ code, ...details }));
}
